[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = ["src/senda/api"]

[tool.coverage.run]
branch = true
source = ["src/senda/api"]

[tool.coverage.report]
omit = ["*/__init__.py"]

[project]
name = "senda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai==1.28.0",
    "pyaudio==0.2.14",
    "python-dotenv==1.1.1",
    "requests==2.32.4",
    "pydub==0.25.1",
    "audioop-lts==0.2.2",

    # API dependencies
    "fastapi==0.116.1",
    "uvicorn[standard]==0.35.0",
    "sqlalchemy==2.0.42",
    "psycopg[binary,pool]==3.2.9",
    "alembic==1.16.4",
    "boto3==1.40.7",
    
    # Authentication dependencies
    "PyJWT==2.10.1",
    "bcrypt==5.0.0",
    "python-multipart==0.0.20",
    "slowapi==0.1.9",
    "pydantic[email]==2.11.7",
    "email-validator==2.3.0",
    
    # Redis
    "redis==6.4.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["models*", "services*", "repositories*", "schemas*", "core*", "routers*", "utils*", "senda*"]


[dependency-groups]
dev = [
    "pre-commit==4.2.0",
    "ruff==0.12.7",
    "pytest==8.4.2",
    "httpx==0.28.1",
    "coverage==7.10.7",
]
