from sqlalchemy.ext.asyncio import AsyncSession

from senda.core.enums import DifficultyLevel
from senda.domain.dtos.course import CourseRecordDTO, CreateCourseDTO
from senda.domain.dtos.course_generation import (
    CourseGenerationRequestDTO,
    CourseStructureDTO,
    LessonStructureDTO,
)
from senda.domain.dtos.user import CreateUserDTO, UserDTO
from senda.domain.repositories.course import ICourseRepository
from senda.domain.repositories.user import IUserRepository


async def create_another_test_user(
    session: AsyncSession, user_repository: IUserRepository
) -> UserDTO:
    create_user_dto = CreateUserDTO(
        username="temp-user", email="temp-user@gmail.com", password="password"
    )
    return await user_repository.add(session=session, create_item=create_user_dto)


async def create_another_test_course(
    session: AsyncSession, course_repository: ICourseRepository, author_id: int
) -> CourseRecordDTO:
    create_course_dto = CreateCourseDTO(
        title="One More Test Course",
        description="Test Description",
        difficulty_level="Beginner",
        tags=["tag1", "tag2", "tag3"],
    )
    return await course_repository.add(
        session=session, author_id=author_id, create_item=create_course_dto
    )


def create_sample_course_structure(
    title: str = "Sample Generated Course",
    description: str = "A test course generated by AI",
    duration_days: int = 7,
    difficulty_level: DifficultyLevel = DifficultyLevel.BEGINNER,
    num_lessons: int = 3,
) -> CourseStructureDTO:
    """
    Helper function to create a sample CourseStructureDTO for testing.

    Args:
        title: Course title
        description: Course description
        duration_days: Number of days for the course
        difficulty_level: Course difficulty level
        num_lessons: Number of lessons to generate

    Returns:
        CourseStructureDTO with sample data
    """
    lessons = [
        LessonStructureDTO(
            title=f"Day {i + 1}: Lesson {i + 1}",
            core_practice=f"Practice {i + 1}",
            key_point=f"Key point {i + 1}",
            tone="calm",
            duration_minutes=10,
            order=i + 1,
        )
        for i in range(num_lessons)
    ]

    return CourseStructureDTO(
        title=title,
        description=description,
        duration_days=duration_days,
        difficulty_level=difficulty_level,
        tags=["test", "generated"],
        lessons=lessons,
    )


def create_sample_generation_request(
    user_id: int = 1,
    prompt: str = "Create a mindfulness course for beginners",
    difficulty_level: DifficultyLevel | None = DifficultyLevel.BEGINNER,
) -> CourseGenerationRequestDTO:
    """
    Helper function to create a sample CourseGenerationRequestDTO for testing.

    Args:
        user_id: ID of the user creating the course
        prompt: Generation prompt
        difficulty_level: Optional difficulty level

    Returns:
        CourseGenerationRequestDTO with sample data
    """
    return CourseGenerationRequestDTO(
        user_id=user_id, prompt=prompt, difficulty_level=difficulty_level
    )


def assert_course_structure_valid(structure: CourseStructureDTO) -> None:
    """
    Helper function to validate that a CourseStructureDTO is properly formed.

    Args:
        structure: CourseStructureDTO to validate

    Raises:
        AssertionError: If structure is invalid
    """
    # Basic structure checks
    assert structure.title, "Course title should not be empty"
    assert structure.description, "Course description should not be empty"
    assert structure.duration_days > 0, "Duration must be positive"
    assert structure.difficulty_level in [
        DifficultyLevel.BEGINNER,
        DifficultyLevel.INTERMEDIATE,
        DifficultyLevel.ADVANCED,
    ], "Invalid difficulty level"

    # Tags checks
    assert isinstance(structure.tags, list), "Tags should be a list"
    assert len(structure.tags) > 0, "Should have at least one tag"

    # Lessons checks
    assert isinstance(structure.lessons, list), "Lessons should be a list"
    assert len(structure.lessons) > 0, "Should have at least one lesson"

    # Validate each lesson
    for i, lesson in enumerate(structure.lessons):
        assert lesson.title, f"Lesson {i} title should not be empty"
        assert lesson.core_practice, f"Lesson {i} core_practice should not be empty"
        assert lesson.key_point, f"Lesson {i} key_point should not be empty"
        assert lesson.tone, f"Lesson {i} tone should not be empty"
        assert lesson.duration_minutes > 0, f"Lesson {i} duration must be positive"
        assert lesson.order > 0, f"Lesson {i} order must be positive"
