"""Add active, tags, and total_lessons to Course model

Revision ID: 1b53289751d9
Revises: ea0874bf8805
Create Date: 2025-08-10 18:24:42.380993

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b53289751d9"
down_revision: Union[str, Sequence[str], None] = "ea0874bf8805"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("total_lessons", sa.Integer(), nullable=True))
    op.add_column(
        "courses",
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("courses", sa.Column("active", sa.Boolean(), nullable=False))
    op.alter_column(
        "courses",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "lessons",
        "course_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lessons",
        "course_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "courses",
        "id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("courses", "active")
    op.drop_column("courses", "tags")
    op.drop_column("courses", "total_lessons")
    # ### end Alembic commands ###
