"""
Integration tests for course generation API endpoint.
Tests the full request/response cycle with validation and auth checks.
"""

import pytest
from fastapi import status
from httpx import AsyncClient

from senda.api.schemas.responses.gemini_schemas import GeminiCourseSchema
from senda.core.enums import DifficultyLevel


class TestCourseGenerationAPI:
    """Test suite for POST /api/courses/generate endpoint"""

    # Mock data for successful course generation
    MOCK_COURSE_SCHEMA = GeminiCourseSchema(
        title="Test Mindfulness Course",
        description="A test course generated by AI",
        duration_days=7,
        difficulty_level=DifficultyLevel.BEGINNER,
        tags=["mindfulness", "test"],
        lessons=[
            {
                "title": "Day 1: Getting Started",
                "core_practice": "Basic breathing",
                "key_point": "Focus on breath",
                "tone": "encouraging",
                "duration_minutes": 10,
                "order": 1,
            },
            {
                "title": "Day 2: Building Awareness",
                "core_practice": "Body scan",
                "key_point": "Notice sensations",
                "tone": "calm",
                "duration_minutes": 12,
                "order": 2,
            },
        ],
    )

    @pytest.mark.anyio
    async def test_generate_course_missing_prompt(self, admin_test_client: AsyncClient):
        """Test validation error for missing prompt"""
        payload = {"difficultyLevel": "beginner"}

        response = await admin_test_client.post("/courses/generate", json=payload)

        assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY

    @pytest.mark.anyio
    async def test_generate_course_invalid_difficulty(
        self, admin_test_client: AsyncClient
    ):
        """Test validation error for invalid difficulty"""
        payload = {"prompt": "Create a course", "difficultyLevel": "invalid_level"}

        response = await admin_test_client.post("/courses/generate", json=payload)

        assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY

    @pytest.mark.anyio
    async def test_generate_course_unauthorized(self, test_client: AsyncClient):
        """Test unauthorized access is rejected"""
        payload = {"prompt": "Create a mindfulness course"}

        response = await test_client.post("/courses/generate", json=payload)

        assert response.status_code == status.HTTP_403_FORBIDDEN

    @pytest.mark.anyio
    async def test_generate_course_user_not_admin(
        self, authorized_test_client: AsyncClient
    ):
        """Test unauthorized access is rejected"""
        payload = {"prompt": "Create a mindfulness course"}

        response = await authorized_test_client.post("/courses/generate", json=payload)
        assert response.status_code == status.HTTP_403_FORBIDDEN

    @pytest.mark.anyio
    async def test_generate_course_empty_prompt(self, admin_test_client: AsyncClient):
        """Test validation error for empty prompt"""
        payload = {"prompt": "", "difficultyLevel": "beginner"}

        response = await admin_test_client.post("/courses/generate", json=payload)

        assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY

    @pytest.mark.anyio
    @pytest.mark.parametrize("difficulty", ["BEGINNER", "INTERMEDIATE", "ADVANCED"])
    async def test_generate_course_all_difficulty_levels(
        self,
        admin_test_client: AsyncClient,
        difficulty: str,
        admin_user,
        mock_gemini_api_globally,
    ):
        """Test course generation with all valid difficulty levels succeeds"""
        mock_gemini_api_globally.return_value = self.MOCK_COURSE_SCHEMA

        payload = {"prompt": "Create a test course", "difficultyLevel": difficulty}

        response = await admin_test_client.post("/courses/generate", json=payload)

        assert response.status_code == status.HTTP_201_CREATED
        data = response.json()

        assert "course" in data
        course = data["course"]
        assert course["title"] == self.MOCK_COURSE_SCHEMA.title
        assert course["description"] == self.MOCK_COURSE_SCHEMA.description
        assert course["author"]["username"] == admin_user.username

        assert "lessons" in course
        lessons = course["lessons"]
        assert len(lessons) == 2
        assert lessons[0]["title"] == self.MOCK_COURSE_SCHEMA.lessons[0].title
        assert lessons[1]["title"] == self.MOCK_COURSE_SCHEMA.lessons[1].title

    @pytest.mark.anyio
    async def test_generate_course_no_difficulty_defaults_to_beginner(
        self, admin_test_client: AsyncClient, admin_user, mock_gemini_api_globally
    ):
        """Test course generation without difficulty level succeeds with default"""
        mock_gemini_api_globally.return_value = self.MOCK_COURSE_SCHEMA

        payload = {"prompt": "Create a test course"}

        response = await admin_test_client.post("/courses/generate", json=payload)

        assert response.status_code == status.HTTP_201_CREATED
        data = response.json()

        assert "course" in data
        course = data["course"]
        assert course["title"] == self.MOCK_COURSE_SCHEMA.title
        assert course["author"]["username"] == admin_user.username

        assert "lessons" in course
        lessons = course["lessons"]
        assert len(lessons) == 2
